const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { content, mimeType, prompt, provider = 'openai' } = await req.json();
    
    if (!content) {
      throw new Error('Document content is required');
    }

    const analysisPrompt = prompt || 'Analyze this document and extract all text content, tables, and relevant information. Provide a structured summary.';

    let analysis: string;

    if (provider === 'gemini') {
      // Gemini Direct API path
      const GEMINI_API_KEY = Deno.env.get('GEMINI_API_KEY');
      if (!GEMINI_API_KEY) {
        throw new Error('Gemini API key not configured');
      }

      console.log('Analyzing document with Gemini 2.5 Pro...');

      // Strip data URI prefix if present to get raw base64
      const base64Data = content.startsWith('data:') 
        ? content.split(',')[1] 
        : content;

      const response = await fetch(
        `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-pro:generateContent?key=${GEMINI_API_KEY}`,
        {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            contents: [{
              role: 'user',
              parts: [
                { text: analysisPrompt },
                { inlineData: { mimeType: mimeType || 'image/png', data: base64Data } },
              ],
            }],
            generationConfig: { maxOutputTokens: 4096 },
          }),
        }
      );

      if (!response.ok) {
        const errorText = await response.text();
        console.error('Gemini analysis error:', response.status, errorText);
        throw new Error(`Document analysis failed: ${response.status}`);
      }

      const data = await response.json();
      analysis = data.candidates?.[0]?.content?.parts?.[0]?.text;
      if (!analysis) throw new Error('No analysis generated by Gemini');

    } else {
      // OpenAI path (default)
      const OPENAI_API_KEY = Deno.env.get('OPENAI_API_KEY');
      if (!OPENAI_API_KEY) {
        throw new Error('Document analysis service not configured');
      }

      console.log('Analyzing document with GPT-4.1...');

      const messages = [
        {
          role: 'user',
          content: [
            { type: 'text', text: analysisPrompt },
            {
              type: 'image_url',
              image_url: {
                url: content.startsWith('data:') ? content : `data:${mimeType};base64,${content}`
              }
            }
          ]
        }
      ];

      const response = await fetch('https://api.openai.com/v1/chat/completions', {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${OPENAI_API_KEY}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          model: 'gpt-4.1',
          messages,
          max_tokens: 4096,
        }),
      });

      if (!response.ok) {
        const errorText = await response.text();
        console.error('Document analysis error:', response.status, errorText);
        throw new Error(`Document analysis failed: ${response.status}`);
      }

      const data = await response.json();
      analysis = data.choices[0].message.content;
    }

    console.log('Document analysis completed');

    return new Response(JSON.stringify({ 
      analysis,
      provider,
      timestamp: new Date().toISOString()
    }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });

  } catch (error) {
    console.error('Error analyzing document:', error);
    return new Response(JSON.stringify({ 
      error: error instanceof Error ? error.message : 'Unknown error' 
    }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});
